# Generated by Django 4.2.7 on 2023-11-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_addedproducts_alter_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('IP', 'In Progress'), ('CL', 'Close')], default='OP', max_length=2),
        ),
    ]
